// src/datas/permissions.jsx
export const permissions = [
  {
    id: 1,
    permission: "VIEW_DASHBOARD",
    type: 1,
    parent: null,
    description: "Access to the dashboard",
    updated: "2025-01-01",
    user_id: 1,
  },
  {
    id: 2,
    permission: "VIEW_DEV_SETTINGS",
    type: 1,
    parent: null,
    description: "Access Dev Settings",
    updated: "2025-01-01",
    user_id: 1,
  },

  {
    id: 3,
    permission: "VIEW_DEV_PERMISSION",
    type: 2,
    parent: 5,
    description: "View Dev Permissions",
    updated: "2025-01-05",
    user_id: 2,
  },
  {
    id: 4,
    permission: "VIEW_USER_MANAGEMENT",
    type: 1,
    parent: null,
    description: "Access to manage users",
    updated: "2025-01-01",
    user_id: 1,
  },
  {
    id: 5,
    permission: "ADD_USER",
    type: 2,
    parent: 2,
    description: "Add new user",
    updated: "2025-01-01",
    user_id: 1,
  },
  {
    id: 6,
    permission: "LIST_USER",
    type: 2,
    parent: 2,
    description: "View all users",
    updated: "2025-01-01",
    user_id: 1,
  },
];
